image: docker-gsrt-tech.af.paloaltonetworks.local/base-image/alpine:latest

stages:
    - build
    - pypi
    - post

before_script:
    - python3 -V               # Print out python version for debugging

pypi:
    stage: pypi
    script:
        - pip3 install -U twine wheel
        - python3 setup.py bdist_wheel
        - twine upload dist/*
    only:
        - master-python3
post:
    stage: post
    trigger:
        project: gsrt-tools/gsrt-utilities-container
        branch: master
